name: 'ServiceNow DevOps Change Automation'
description: 'Pause/Resume Workflow Run based on ServiceNow Change Approval Status'
inputs:
  instance-url: 
    description: 'ServiceNow Instance URL'
    required: true
  devops-integration-user-name:
    description: 'Devops Integration User Name'
    required: false
  devops-integration-user-password:
    description: 'Devops Integration User Password'
    required: false
  devops-integration-token:
    description: 'Devops Integration Token'
    required: false
  tool-id:
    description: 'Orchestration Tool Id'
    required: true
  job-name:
    description: 'Display Name of the Job'
    required: true
  context-github:
    description: 'Github Context'
    required: true
  timeout:
    description: 'The max. time in seconds to wait until the action should fail.'
    required: false
    default: '3600'
  interval:
    description: 'The time in seconds to wait between trying the API.'
    required: false
    default: '100'
  change-request:
    description: 'The customized inputs to create change with the requested details.'
    required: true
  changeCreationTimeOut:
    description: 'The max. time in seconds to wait until change created.'
    required: false
    default: '3600'
  abortOnChangeCreationFailure:
    description: 'This value will be used to resume or abort the pipeline if the change is not created within the mentioned time period in changeCreationTimeOut. '
    required: false
    default: true
  abortOnChangeStepTimeout:
    description: 'This value will be used to resume or abort the pipeline after a timeout has occurred in case a change step is still in a pending state.'
    required: false
    default: true
  deployment-gate:
    description: 'The customized inputs to process deployment gate job related change.'
    required: false
branding:
  icon: 'refresh-ccw'
  color: 'green'
runs: 
  using: 'node16'
  main: 'dist/index.js'
